name: api
recipe: drupal10
config:
  webroot: public_html
  composer_version: 2
  xdebug: false

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - corpusdata
  #mailhog:
  #  type: mailhog:v1.0.0
  #  portforward: true
  #  hogfrom:
  #    - appserver
  appserver:
    type: php:8.4
    xdebug: true
    config:
      php: .vscode/php.ini
    via: apache
    version: 2.4
    webroot: public_html
    build:
      - composer install
      - cp public_html/sites/default/example.settings.local.php public_html/sites/default/settings.local.php
    scanner: false
  corpusdata:
    type: mariadb:10.6
    scanner: false
  database:
    type: mariadb:10.6
    scanner: false
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app --uri=https://api.lndo.site
