name: api
recipe: drupal9
config:
  webroot: public_html
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - source_database
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php:7.4
    via: apache
    version: 2.4
    webroot: public_html
  source_database:
    type: mysql
tooling:
  uli:
    service: appserver
    description: one-time login command
    cmd: drush uli --uri=https://api.lndo.site
  cr:
    service: appserver
    description: clear the Drupal cache
    cmd: /app/scripts/lando/cr.sh
