name: api
recipe: drupal9
config:
  webroot: public_html
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - source_database
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php:8.2
    config:
      php: lando/php.ini
    via: apache
    version: 2.4
    webroot: public_html
  source_database:
    type: mysql
tooling:
  go:
    service: appserver
    description: Perform setup stuff for local development
    cmd:
      - cp drush/example.drush.yml drush/drush.yml
      - cp public_html/sites/default/example.settings.local.php public_html/sites/default/settings.local.php
      - composer install
  drush:
    service: appserver
    cmd: drush --root=/app --uri=https://api.lndo.site
