name: api
recipe: drupal10
config:
  webroot: public_html
  composer_version: 2
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - source_database
  #mailhog:
  #  type: mailhog:v1.0.0
  #  portforward: true
  #  hogfrom:
  #    - appserver
  appserver:
    type: php:8.3
    config:
      php: lando/php.ini
    via: apache
    version: 2.4
    webroot: public_html
    build:
      - composer install
      - cp public_html/sites/default/example.settings.local.php public_html/sites/default/settings.local.php
  source_database:
    type: mysql
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app --uri=https://api.lndo.site
