name: api
recipe: drupal8
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php
tooling:
  uli:
    service: appserver
    description: one-time login command
    cmd: drush uli --uri=https://api.lndo.site
  cr:
    service: appserver
    description: clear the Drupal cache
    cmd: /app/scripts/lando/cr.sh
