name: api
recipe: drupal9
config:
  webroot: public_html
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - source_database
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php:8.0
    via: apache
    version: 2.4
    webroot: public_html
  source_database:
    type: mysql
