name: api
recipe: drupal11
config:
  php: 8.4
  webroot: public_html
  composer_version: 2
  xdebug: false
services:
  #mailhog:
  #  type: mailhog:v1.0.0
  #  portforward: true
  #  hogfrom:
  #    - appserver
  appserver:
    config:
      php: .vscode/php.ini
    via: apache
    version: 2.4
    scanner: false
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app --uri=https://api.lndo.site
