name: api
recipe: drupal8
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
      - source_database
  mailhog:
    type: mailhog:v1.0.0
    portforward: true
    hogfrom:
      - appserver
  appserver:
    type: php
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "http://api.lndo.site"
        SYMFONY_DEPRECATIONS_HELPER: 'disabled' # Temporary workaround to use deprecated methods.
        SIMPLETEST_DB: 'mysql://database:database@database/database'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
        BROWSERTEST_OUTPUT_DIRECTORY: '/app/sites/simpletest/browser_output'
        DRUSH_OPTIONS_ROOT: '/app'
        DRUSH_OPTIONS_URI: 'https://api.lndo.site'
  database:
    creds:
      user: database
      password: database
      database: database
  chrome:
    type: compose
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  source_database:
    type: mysql
tooling:
  uli:
    service: appserver
    description: one-time login command
    cmd: drush uli --uri=https://api.lndo.site
  cr:
    service: appserver
    description: clear the Drupal cache
    cmd: /app/scripts/lando/cr.sh
  test:
    service: appserver
    cmd: "php /app/vendor/bin/phpunit -c /app/phpunit.xml"
