crow_users.settings:
  type: config_object
  label: 'Crow users settings'
  mapping:
    on:
      type: boolean
      label: 'Enable notifications'
    offline_survey:
      type: text
      label: 'URL for offline survey'
    assignee_ids:
      type: text
      label: 'Assignee IDs'
    project:
      type: text
      label: 'Project'
    list:
      type: text
      label: 'List'
    description_standard:
      type: text
    description_offline:
      type: text
    description_full_text_access:
      type: text
    description_export:
      type: text
