_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  basecamp_api: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  ckeditor5: 0
  config: 0
  config_filter: 0
  config_update: 0
  consumers: 0
  contextual: 0
  corpus_api_texts: 0
  corpus_frequency: 0
  corpus_importer: 0
  corpus_search: 0
  crow_users: 0
  csv_serialization: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  facets: 0
  facets_rest: 0
  field: 0
  file: 0
  filter: 0
  honeypot: 0
  image: 0
  inline_form_errors: 0
  language: 0
  login_emailusername: 0
  mailsystem: 0
  mimemail: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  rabbit_hole: 0
  recaptcha: 0
  rest: 0
  rest_feedback_endpoint: 0
  restui: 0
  rh_node: 0
  role_delegation: 0
  search_api: 0
  search_api_db: 0
  search_api_lemma: 0
  serialization: 0
  simple_oauth: 0
  simple_oauth_password_grant: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  userprotect: 0
  views_data_export: 0
  views_ui: 0
  views: 10
  corpus: 1000
theme:
  claro: 0
  crow_theme: 0
profile: corpus
