_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: phpmailer_smtp
  formatter: phpmailer_smtp
modules:
  sendgrid_integration: {  }
  smtp:
    none:
      sender: phpmailer_smtp
      formatter: phpmailer_smtp
  crow_users:
    user_report:
      sender: phpmailer_smtp
      formatter: mime_mail
