_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
modules:
  sendgrid_integration: {  }
  smtp:
    none:
      sender: SMTPMailSystem
      formatter: SMTPMailSystem
  crow_users:
    user_report:
      sender: SMTPMailSystem
      formatter: mime_mail
