theme: current
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration: {  }
  smtp:
    none:
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
  crow_users:
    user_report:
      formatter: htmlmail
      sender: SMTPMailSystem
