theme: current
defaults:
  sender: php_mail
  formatter: php_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration: {  }
  smtp:
    none:
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
  crow_users:
    user_report:
      formatter: mime_mail
      sender: SMTPMailSystem
