_core:
  default_config_hash: rLKGzzC9TqjbEZiBoiyMpOSyZgldADa5SzvbA2gQDxE
format: standard_html
name: Crow
mail: writecroworg@gmail.com
linkonly: false
textonly: false
sitestyle: false
simple_address: false
preserve_class: false
advanced:
  incoming: false
  key: OlZkBAq60h-KFlwPlupF34y2AHqR2nd_2C7Bc1VBqEQ
