login_redirection:
  anonymous: null
  authenticated: /user/login
  administrator: /user/login
  full_text_access: /user/login
  basic_search_access: /user/login
  export_access: /user/login
  manager: /admin/people
  content_manager: /admin/content
exclude_urls: ''
