access_token_expiration: 7200
refresh_token_expiration: 1209600
remember_clients: true
_core:
  default_config_hash: iIf5HmjnxW8tLdod1EQ19q4RQ5mkg-r5wBn2QFmitr8
public_key: null
private_key: null
token_cron_batch_size: 0
authorization_code_expiration: 300
use_implicit: true
disable_openid_connect: false
