access_token_expiration: 1800
refresh_token_expiration: 1209600
remember_clients: true
_core:
  default_config_hash: iIf5HmjnxW8tLdod1EQ19q4RQ5mkg-r5wBn2QFmitr8
public_key: null
private_key: null
token_cron_batch_size: 0
