<?php

/**
 * @file
 * Contains search_api_lemma.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function search_api_lemma_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the search_api_lemma module.
    case 'help.page.search_api_lemma':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search index lemmatizer processor for Search API') . '</p>';
      return $output;

    default:
  }
}
