<?php

/**
 * @file
 * Contains corpus_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function corpus_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the corpus_search module.
    case 'help.page.corpus_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search API for a Corpus Dataset') . '</p>';
      return $output;

    default:
  }
}

if (!function_exists('mb_ucfirst')) {

  /**
   * Helper function for UTF8-multibyte character manipulation.
   */
  function mb_ucfirst($str, $encoding = "UTF-8", $lower_str_end = TRUE) {
    $first_letter = mb_strtoupper(mb_substr($str, 0, 1, $encoding), $encoding);
    $str_end = "";
    if ($lower_str_end) {
      $str_end = mb_strtolower(mb_substr($str, 1, mb_strlen($str, $encoding), $encoding), $encoding);
    }
    else {
      $str_end = mb_substr($str, 1, mb_strlen($str, $encoding), $encoding);
    }
    $str = $first_letter . $str_end;
    return $str;
  }

}
