crow_users.settings:
  type: config_object
  label: 'Crow users settings'
  mapping:
    assignee_ids:
      type: text
      label: 'Assignee IDs'
    project:
      type: text
      label: 'Project'
    list:
      type: text
      label: 'List'
